CPPFLAGS += -I.
CFLAGS += -O2 -Wall -g --target=x86_64-elf -ffreestanding
#@range_begin(app_flags)
CXXFLAGS += -O2 -Wall -g --target=x86_64-elf -fno-exceptions -ffreestanding \
            -fno-rtti -std=c++2a -mcmodel=large
LDFLAGS += --entry main -z norelro --image-base 0xffff800000000000 --static
#@range_end(app_flags)

.PHONY: all
all: $(TARGET)

$(TARGET): $(TARGET).o Makefile
	ld.lld $(LDFLAGS) -o $@ $< -lc -lc++ -lc++abi

%.o: %.cpp Makefile
	clang++ $(CPPFLAGS) $(CXXFLAGS) -c $< -o $@
